### ISSUE TITLE
Define Weather Categories

### ISSUE THREAD

**Issue by jviotti** [IversityMobileTeam/tweet-the-weather#1]
Our application will serve different tweets depending on temperature range of the user's weather.

I suggest creating weather ranges and give each a name.

This work already started in the following shared Google Docs spreadsheet: https://docs.google.com/spreadsheets/d/1ilTqsWQcV2YAwvUimEZym7fZB0sy5RKpofuvBJ8eC8c/edit#gid=0.

Any suggestions on this? Let's discuss and complete the spreadsheet in this issue.

**Comment by jviotti** [comment]
All categories have nice names already. 

`0º C to 10 ºC` has two possible names: Chilly and Frosty.

Which one do you like more?

**Comment by andrIvash** [comment]
Frosty
15.04.2014 20:20 пользователь "Juan Cruz Viotti" notifications@github.com
написал:

**Comment by jviotti** [comment]
I like frosty too. Let's wait until 2 more comment. If we all agree with frosty I'll close the issue and move this information to the wiki.

**Comment by mytobygithub** [comment]
frosty 
is awesome

**Comment by mytobygithub** [comment]
frosty is awesome

 

Gesendet: Dienstag, 15. April 2014 um 20:29 UhrVon: "Juan Cruz Viotti" notifications@github.comAn: IversityMobileTeam/tweet-the-weather tweet-the-weather@noreply.github.comBetreff: Re: [tweet-the-weather] Define Weather Categories (#1)

I like frosty too. Let's wait until 2 more comment. If we all agree with frosty I'll close the issue and move this information to the wiki.

**Comment by mytobygithub** [comment]
Something that comes to my mind, when i look the mock up.
Normally the weather apps offers more than just a temperature, i guess the easiest solution is to give the user more options by offering more tweets for each temperature range. for example depending if it has 10 degrees with sun or rain....
or you think is better he send two tweets about the temperature 10-20 just enjoy.....and the second the sun 
or 10-20 just enjoy the rain....
this is just an idea we can discuss, i don´t wanna make the app more difficult when necessary is just an idea.....

**Comment by jviotti** [comment]
Nice, I kept **Frosty** in the spreadsheet.

@mytobygithub That's a very good comment and something we didn't consider. The temperature alone is not a complete measure of the current weather. We should also take into account:
- Humidity.
- Wind.
- Rain/Storm.
- Sun.
- etc.

In that case I propose that each Tweet will have "tags" describing what is it about. For example:

``` json
{
  "text": "My Tweet",
  "tags": [ "rain", "high-wind", "cloudy", "frosty" ]
}
```

Then we will only show the tweets that matches the current weather depending on it's tags.

Also, in the Home View list, we can include some icons like a "big finger up" for positive tweets and a "big finger down" for negative ones.

We can describe if the tweet is positive or negative with a boolean JSON field:

``` json
{
  "text": "My Tweet",
  "tags": [ "rain", "high-wind", "cloudy", "frosty" ],
  "positive": true
}
```

Another alternative would be to show only two buttons in the home page, saying something like "I like the weather", or "I don't like the weather". Depending on what button the user clicks, he'll be redirected to a list containing all positive or all negative tweets.

What do you think? I think last idea is much more simpler for the user.

I'll also update the `Tweet Model` issue (#3) to describe the tags array.

**Comment by mytobygithub** [comment]
i think is a good and easy solution.

**Comment by jviotti** [comment]
Updated mockup:

![tweet the weather_3](https://cloud.githubusercontent.com/assets/2192773/2723331/dae5e3dc-c592-11e3-875e-1ed8afa0d944.png)

What do you think? Once we discuss about humidity, wind, etc further we can plan how to add them somewhere in the home page.

As the home page doesn't contains the list anymore, it doesn't depends on Tweet Store. If you agree I'll edit the issue so you can already start working on the layout.

**Comment by andrIvash** [comment]
Cool.
16.04.2014 21:14 пользователь "Juan Cruz Viotti" notifications@github.com
написал:

**Comment by jviotti** [comment]
Will close this now. We will discuss tags later on.
