### ISSUE TITLE
Implement TweetList view

### ISSUE THREAD

**Issue by jviotti** [IversityMobileTeam/tweet-the-weather#12]
Implement the Tweet List view according to design (second screen):

![tweet the weather_3](https://cloud.githubusercontent.com/assets/2192773/2734598/38eb35e0-c656-11e3-823c-d92d5cc1e4f0.png)

You should generate Tweet List view using `Sencha Cmd`.

The view should contains:
- A header with a back button.
- A list that connects to `Tweet Store` (#4).
- Each list item should contains an arrow at the right as shown in the design.

**Comment by andrIvash** [comment]
changes are made

**Comment by jviotti** [comment]
There is no need to close your older pull request. The changes that you made will automatically be included. Did you make the changes?

**Comment by andrIvash** [comment]
yes

**Comment by jviotti** [comment]
Where are they? I can't see them on the pull request.

**Comment by andrIvash** [comment]
and now ?

**Comment by jviotti** [comment]
I can see them now. Added a bunch of more comments. The main issue was that I think you misinterpreted my comment about brackets and square brackets being in a new line.

Your initial commit contained the following pattern:

``` js
items: [{
  ...
}]
```

In your latest commit you did the following pattern:

``` js
items: 
[
  {
    ...
  }
]
```

That is almost correct, but the initial square bracket should be in the same line as the field name:

``` js
items: [
  {
    ...
  }
]
```

**Comment by jviotti** [comment]
Merged.
