### ISSUE TITLE
Polish Application Mockups

### ISSUE THREAD

**Issue by jviotti** [IversityMobileTeam/tweet-the-weather#2]
I created a new repo to hold design files and mockups: https://github.com/IversityMobileTeam/tweet-the-weather-design.

I need your feedback to polish the mockups and move to the next step. Please let me know what you think.
![tweet the weather](https://cloud.githubusercontent.com/assets/2192773/2695581/330aac6c-c3d8-11e3-82e8-65e2c9e67ecb.png)

**Comment by jviotti** [comment]
If anybody does design, new mockups would be welcomed.

**Comment by andrIvash** [comment]
i like this idea..... simple and functional

2014-04-14 16:25 GMT+03:00 Juan Cruz Viotti notifications@github.com:

**Comment by mytobygithub** [comment]
awesome looks really great.

maybe we can show in screen the place for which the weather is.
and we need think if we wanna give this information in the tweet as well or not .

But the design is really great easy to understand :-)

**Comment by mytobygithub** [comment]
awesome looks really great.

maybe we can show in screen the place for which the weather is.
and we need think if we wanna give this information in the tweet as well or not .

But the design is really great easy to understand :-)

 

 

 

 

 

 

 

 

Gesendet: Montag, 14. April 2014 um 15:25 UhrVon: "Juan Cruz Viotti" notifications@github.comAn: IversityMobileTeam/tweet-the-weather tweet-the-weather@noreply.github.comBetreff: [tweet-the-weather] Polish Application Mockups (#2)

I created a new repo to hold design files and mockups: https://github.com/IversityMobileTeam/tweet-the-weather-design.

I need your feedback to polish the mockups and move to the next step. Please let me know what you think.

**Comment by jviotti** [comment]
Awesome thanks!

> maybe we can show in screen the place for which the weather is.
> and we need think if we wanna give this information in the tweet as well or not

I think that are awesome ideas. I'll edit the mockups to reflect current place in a second.

About giving the information in the tweet I can think of the following alternatives:
- We can append **from London/UK** or something like that at the end of the tweet, although appending that to every tweet will make it look automatised and not human. 
- Include placeholders in our tweets that will get replaced for current city. For example:

`I like current weather in {CITY}, it's perfect!`

Then `{CITY}` will be replaced by the city name itself, for example:

`I like current weather in Buenos Aires, it's perfect!`

What do you think?

**Comment by jviotti** [comment]
Mockup updated to reflect current city:

![tweet the weather_2](https://cloud.githubusercontent.com/assets/2192773/2707313/6a7667c2-c4a0-11e3-9552-a59f583b7b9e.png)

**Comment by jviotti** [comment]
I'll create an issue to implement the home page and some extras.

**Comment by arin-banerjee** [comment]
Looking perfect...!!!

**Comment by andrIvash** [comment]
Good idea
15.04.2014 16:05 пользователь "Juan Cruz Viotti" notifications@github.com
написал:

**Comment by jviotti** [comment]
Will close this issue as it already served well it's purpose. We can open new issues for certain parts of the design.
