### ISSUE TITLE
Find a free Weather API

### ISSUE THREAD

**Issue by jviotti** [IversityMobileTeam/tweet-the-weather#7]
The API should:
- Be able to return (real time) current weather
- Be able to find a city by `{COUNTRY}/{CITY}` schema and/or latitude/longitude. 
- Be able to return current temperature in Celsius degrees.

**Comment by andrIvash** [comment]
worldweatheronline.com ?

**Comment by jviotti** [comment]
@andrIvash Does worldweatheronline accepts requests by latitude/longitude?

**Comment by andrIvash** [comment]
yes

**Comment by jviotti** [comment]
Just looked at the documentation. Looks great. Will close this issue and open a new one for API integration.
